services:
  ros2_dev:
    # 1. BUILD & IDENTITY
    build: .
    container_name: ros2_thesis_env
    volumes:
      - ./src:/home/ros_ws/src
      - ./simulation_entrypoint.sh:/home/ros_ws/simulation_entrypoint.sh
      - ./dashboard:/home/ros_ws/dashboard # Compartir la carpeta de la web
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GAZEBO_MODEL_PATH=/home/ros_ws/src/robots
      - GAZEBO_RESOURCE_PATH=/usr/share/gazebo-11
      - GAZEBO_MODEL_DATABASE_URI=""
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  dashboard:
    build: ./dashboard
    container_name: ros2_dashboard
    volumes:
      - ./dashboard:/usr/share/nginx/html # Sincronización en tiempo real para desarrollo
    ports:
      - "8080:80"
