/**:
  ros__parameters:

    # Robot type: "community_arm" or "open_manipulator"
    robot_type: "community_arm"

    # Set this to true to input start/goal in degrees, or false for radians
    angles_in_degrees: true

    # Set to true to use the static start configuration below.
    # Set to false to read start dynamically from the GUI sliders.
    use_static_start: true

    # START CONFIGURATION (Point A) in DEGREES
    start:
      - 120.0      # base_yaw_joint (yaw)
      - -45.0    # shoulder_pitch_joint (shoulder pitch)
      - 20.0     # elbow_pitch_joint (elbow pitch)

    # GOAL CONFIGURATION (Point B) in DEGREES
    goal:
      - -40.0      # base_yaw_joint (yaw)
      - -45.0     # shoulder_pitch_joint (shoulder pitch)
      - 90.0    # elbow_pitch_joint (elbow pitch)


    # Grid resolution (lower means more precision but slower planning)
    step_size_deg: 8.0
    
    # Distance threshold in meters for URDF sphere thinning (e.g. 0.015 = 1.5 cm)
    sphere_thinning_dist: 0.01

    # Algorithm: "astar" or "rrt"
    planner_type: "astar"

    # Metric/Heuristic: "L1" (Manhattan) or "L2" (Euclidean)
    heuristic_type: "L1"

    # End-effector behavior
    use_horizontal_constraint: false

    # Environment obstacles
    use_obstacles: true

    # Obstacle type: "box_obstacle", "narrow_passage", "u_obstacle", "toroidal_wall"
    obstacle_type: "box_obstacle"
