/**:
  ros__parameters:

    # Robot type: "community_arm" or "open_manipulator"
    robot_type: "community_arm"

    # Set this to true to input start/goal in degrees, or false for radians
    angles_in_degrees: true

    # Set to true to use the static start configuration below.
    # Set to false to read start dynamically from the GUI sliders.
    use_static_start: false

    # START CONFIGURATION (Point A) in DEGREES (World coordinates)
    start:
      - 0.0        # Base Yaw (aligned with X axis)
      - 90.0       # Shoulder Pitch (90.0 = vertical)
      - 0.0        # Elbow Pitch (0.0 = parallel/aligned)

    # GOAL CONFIGURATION (Point B) in DEGREES (World coordinates)
    # TODO: Is this goal point useful? Currently we are using the GUI sliders to input the goal point.
    goal:
      - 72.0       # Base Yaw (angle in world)
      - 135.0      # Shoulder Pitch (angle in world)
      - 90.0       # Elbow Pitch (angle in world)


    # Link lengths in meters (for kinematics solver)
    link_lengths:
      base_height: 0.065
      lower_shank: 0.140
      upper_shank: 0.140

    # Grid resolution (lower means more precision but slower planning)
    # TODO: Is this parameter still used? We have computed several C-space maps for different resolutions.
    step_size_deg: 15.0

    # Yoshikawa manipulability threshold for singularity avoidance (0.0 = disabled)
    # Recommended default: 0.0005. Values below this will be classified as C_obs (obstacle/invalid).
    singularity_threshold: 0.0005

    # Rate in Hz to publish waypoints during trajectory animation (default: 50.0 Hz)
    animation_rate_hz: 50.0
    
    # Distance threshold in meters for URDF sphere thinning (e.g. 0.015 = 1.5 cm)
    # TODO: Is this parameter the best way to compute collisions?
    phere_thinning_dist: 0.015

    # Algorithm: "astar" or "rrt"
    # TODO: Is this parameter still used? We use the GUI for this. 
    planner_type: "astar"

    # Metric/Heuristic: "L1" (Manhattan) or "L2" (Euclidean)
    # TODO: Is this parameter still used? We use the GUI for this. 
    heuristic_type: "L1"

    # End-effector behavior
    # TODO: This is not useful, we might need to remove it. 
    use_horizontal_constraint: false

    # Environment obstacles
    #TODO: Clarify the use of this parameter.
    use_obstacles: true

    # Obstacle type: "box_obstacle", "narrow_passage", "u_obstacle", "toroidal_wall"
    obstacle_type: "no_obstacles"

    # Joint origin offsets in degrees (relative to world axes)
    joint_offsets:
      base_yaw: 32.0694
      shoulder_pitch: 90.0
      elbow_pitch: 0.0

    # Joint rotation direction multipliers (1 or -1) relative to world axes
    joint_directions:
      base_yaw: -1
      shoulder_pitch: -1
      elbow_pitch: 1
